###
GET http://localhost:9000/api HTTP/1.1

###
POST  http://localhost:9000/api HTTP/1.1
Content-Type: application/json

{
    "titulo":"los siete habitos de laas personas altamente efectivas",
    "autor":"stephen covey",
    "edicion":6
}

###
DELETE http://localhost:9000/api/2 HTTP/1.1

###
PUT http://localhost:9000/api/3 HTTP/1.1
Content-Type: application/json

{
    "titulo":"una breve historia en el tiempo ",
    "autor":"stephen hawking",
    "edicion":5
}